site_name: My Docs

theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
    accent: deep purple
  language: pt-BR

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
